# Generated by Django 2.1.5 on 2019-01-30 04:04

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constance',
            name='value',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
