name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    if: github.repository == 'jazzband/django-constance'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U build setuptools twine wheel

      - name: Build package
        run: |
          python -m build
          twine check dist/*

      - name: Upload packages to Jazzband
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.11.0
        with:
          user: jazzband
          password: ${{ secrets.JAZZBAND_RELEASE_KEY }}
          repository_url: https://jazzband.co/projects/django-constance/upload
